[phases.setup]
nixPkgs = [
  'php82',
  'php82Extensions.intl',
  'php82Extensions.zip',
  'php82Extensions.exif',
  'php82Extensions.pdo',
  'php82Extensions.pdo_pgsql',
  'php82Extensions.mbstring',
  'php82Extensions.gd',
  'php82Extensions.dom',
  'php82Extensions.curl',
  'php82Extensions.fileinfo',
  'php82Extensions.bcmath',
  'php82Extensions.opcache'
]

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[phases.build]
cmds = [
  'php artisan config:clear',
  'php artisan cache:clear'
]

[start]
cmd = 'php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=$PORT'