[phases.setup]
nixPkgs = [
  'php83',
  'php83Extensions.intl',
  'php83Extensions.zip',
  'php83Extensions.exif',
  'php83Extensions.pdo',
  'php83Extensions.pdo_pgsql',
  'php83Extensions.mbstring',
  'php83Extensions.gd',
  'php83Extensions.dom',
  'php83Extensions.curl',
  'php83Extensions.fileinfo'
]

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-req=ext-intl --ignore-platform-req=ext-zip --ignore-platform-req=ext-exif']

[phases.build]
cmds = ['php artisan config:cache', 'php artisan route:cache']

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'